spring:
  application:
    name: springboot-annotations
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    defer-datasource-initialization: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect

datasource:
  url: jdbc:h2:mem:testdb
  driver-class-name: org.h2.Driver
  username: sa
  password: password

h2:
  console:
    enabled: true

server:
  port: 8080